# Generated by Django 2.1.7 on 2019-02-26 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=3)),
                ('sub1_name', models.CharField(max_length=10)),
                ('sub2_name', models.CharField(max_length=10)),
                ('sub3_name', models.CharField(max_length=10)),
                ('sub4_name', models.CharField(max_length=10)),
                ('sub5_name', models.CharField(max_length=10)),
                ('sub6_name', models.CharField(max_length=10)),
                ('sub7_name', models.CharField(max_length=10)),
                ('sub8_name', models.CharField(max_length=10)),
                ('sub9_name', models.CharField(max_length=10)),
                ('sub10_name', models.CharField(max_length=10)),
                ('sub11_name', models.CharField(max_length=10)),
                ('sub12_name', models.CharField(max_length=10)),
                ('sub13_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=3)),
                ('sub1', models.CharField(max_length=10)),
                ('sub2', models.CharField(max_length=10)),
                ('sub3', models.CharField(max_length=10)),
                ('sub4', models.CharField(max_length=10)),
                ('sub5', models.CharField(max_length=10)),
                ('sub6', models.CharField(max_length=10)),
                ('sub7', models.CharField(max_length=10)),
                ('sub8', models.CharField(max_length=10)),
                ('sub9', models.CharField(max_length=10)),
                ('sub10', models.CharField(max_length=10)),
                ('sub11', models.CharField(max_length=10)),
                ('sub12', models.CharField(max_length=10)),
                ('sub13', models.CharField(max_length=10)),
            ],
        ),
    ]
