# Generated by Django 2.1.7 on 2019-02-26 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewresults', '0002_auto_20190226_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewresults.Branch'),
        ),
    ]
